### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by DimitryVo** [ClemaX/ft_linux#1]
Hello, result of  make all command: 

pkg_extract: Extracting make-4.4.tar.gz to make-4.4...
pkg_extract: Building make-4.4...
/home/lfs/utils/package.sh: line 21: /mnt/lfs/sources/make-ca-1.7.tar.xz: Permission denied
error_handler: /home/lfs/utils/package.sh:21: "$builder" "$name" returned with unexpected exit status 0
error_handler: ./build.sh:87: env -i LFS="$LFS" LFS_VERSION="$LFS_VERSION" LFS_LOCALVERSION="$LFS_LOCALVERSION" LFS_HOSTNAME="$LFS_HOSTNAME" XZ_DEFAULTS="$XZ_DEFAULTS" BASH_ENV='~/.bashrc' su lfs -c '~/build_toolchain.sh' returned with unexpected exit status 0

Could you recommend anything?

**Comment by ClemaX** [comment]
Hi, thank you for pointing put the issue. I added some packages ans the following code is now broken due to `make-ca-xxx.tar.xx` matching `make*.tar*`.

src/host/lfs/build_toolchain.sh:
```sh
for pkg in m4 ncurses bash coreutils diffutils file findutils gawk grep \
	gzip make patch sed tar xz
do
	pkg_extract "$LFS/sources/"$pkg*.tar*		pkg_build_$pkg
done
```

**Comment by ClemaX** [comment]
This should now be fixed in the latest commit.
