### ISSUE TITLE
About use img

### ISSUE THREAD

**Issue by DimitryVo** [ClemaX/ft_linux#3]
Hello, thank you for answer. I made some corrections and I have got img file. I have imported it to Proxmox VM  (add hdd by command: qm importdisk 100 lfs.img hdd) and after I have started VM I see Booting message with ~16% CPU usage, but without screen change about 2min. Could you recommend anything?

**Comment by ClemaX** [comment]
Using these steps the VM starts up, but the virtual graphics device is not recognized:

- Create proxmox VM with OVMF UEFI and without any disks
- Run `qm importdisk 100 /tmp/lfs.img local-lvm` on proxmox
- Edit VM disk to use SATA
- Edit VM `Boot Order` in Options to have `sata0` first
- Boot VM and hit escape to enter configuration
- Untick `Attempt Secure Boot` in Device Manager > Secure Boot Configuration
- Go back to the main menu using escape and select the `Reset` option


The kernel configuration did not include the drivers for the default Proxmox graphics device (Bochs), but I now added it.

You can edit your kernel configuration using `make kernel-menuconfig` or execute the following commands to pull the new sources and rebuild the kernel:

```sh
# Pull updated sources
git pull

# Invalidate build
rm -f dist/build-id

# Remove cached linux kernel package to rebuild with new config
make CMD='rm -rf /cache/pkg/linux'

# Rebuild the image
make
```

The image will be built a lot faster if you kept the docker cache volume, as it contains sources and built packages.
When using `make kernel-menuconfig`, the linux kernel package cache is deleted automatically.

If you don't want to rebuild the kernel you can also try with other supported devices types like VMWare or SPICE (QXL).
