### ISSUE TITLE
About network

### ISSUE THREAD

**Issue by DimitryVo** [ClemaX/ft_linux#4]
Hello, thank you for your recommends. I run VM successful, but without network and package manager.
I have added to VM NIC RTL8139, but don't see its network interface in system. In additional I don't see 
dhcpclient and net config with package manager, for example, apt.  Could you recommend anything?

**Comment by ClemaX** [comment]
Hi, you may need to configure the kernel to enable the drivers for your NIC, or you can change the NIC to use (I think I enabled VirtIO and Intel).

To configure the network, you can use the `lfs-config` command, which supports dhcp and static IP configuration. Afterwards, you need to reboot the system or manually enable the network service using `/etc/init.d/network start`.

For more information about DHCP: https://www.linuxfromscratch.org/blfs/view/11.3/basicnet/dhcp.html


The package manager is called `pkg`, but it is very rudimentary.
You can create your own packages by looking at examples in the src/lfs/packages folder in the repository.

To install a package, navigate to the folder containing the .pkg file and execute `pkg build [pkg-name]` followed by `pkg install [pkg-name]`.

If you need a wide range of packages out of the box, you'll need to use another distribution.
